### PR TITLE
Update class-indieauth-authorize.php

### PR DESCRIPTION
**Pull request by janboddez**
Even though the default value for `$error` _is_ `null`, we should probably not make assumptions about expected _return values_. By returning `$error` rather than a hardcoded `null`, we respect other plugins' possible changes.

Jetpack, for instance, calls this filter like so (i.e., with `$error` equal to `true`): https://github.com/Automattic/jetpack/blob/e29cee2d08516e93486e4dcd0b102244e7609ed4/projects/plugins/jetpack/_inc/lib/admin-pages/class.jetpack-admin-page.php#L190-L195. May be weird, but if we then return `null`, things break.

### CODE REVIEW

**Comment by janboddez** [comment]
Oh, forgot to mention that this should fix #265.

**Comment by janboddez** [comment]
> May be weird, but if we then return `null`, things break.

Turns out `true` is actually valid ... (https://developer.wordpress.org/reference/hooks/rest_authentication_errors/). Either way, probably safest to just allow other plugins to do their thing and just return whatever value we were passed (or an error, of course)!

**Review by pfefferle — APPROVED** [review]
👍

**Comment by janboddez** [comment]
Made a few more changes.

Just one, actually, the rest was updating the PHPDoc.

Anyway, so, I was wondering. If the `$error` arg is in fact non-empty (because the filter was called, like Jetpack does, with `true` as its first argument), should we _always_ simply return it?

Maybe it's equally "safe" to still allow IndieAuth to return any error it encountered? Or rather, if this isn't an "IndieAuth request," no error would get set anyway (at least, that's what I'm assuming), and as a result the `$error` arg would be returned unchanged regardless. If that's the case, there's no need for the "empty" check. (I think?)

**Comment by dshanske** [comment]
Looks good to me.

**Pull request merged**
