### PR TITLE
Switch to returning home_url as me over site_url

### PR DESCRIPTION
**Pull request by dshanske**
It has been pointed out this is inaccurate.

### CODE REVIEW

**Review by pfefferle — APPROVED** [review]

**Comment by metbril** [comment]
I found a reference to site_url

https://github.com/indieweb/wordpress-indieauth/blob/fbf3a918f6469452193ba14a2aafd1ccb0bb4478/includes/functions.php#L200

Shouldn't that also be changed?

**Comment by dshanske** [comment]
@metbril Would your site be on a different domain than your home?

**Comment by metbril** [comment]
My site is hosted from root (`/`). You can browse, for example, an archive from https://robertvanbregt.nl/2018/

The software is installed in /wp. So the admin panel lives in https://robertvanbregt.nl/wp/wp-admin

(Although https://robertvanbregt.nl/admin will redirect just fine)

**Comment by dshanske** [comment]
So this line you mentioned only checks for same domain

**Comment by metbril** [comment]
I see. I'm still unsure if it needs updating. We'll wait and see. It's up to you. I only mentioned it because I ran into it when searching for the string.

**Pull request merged**
