### PR TITLE
Tweaks

### PR DESCRIPTION
**Pull request by dshanske**
This PR does the following

* Uses @pfefferle code from webfinger to replace the original code to find an author URL from an author post URL if provided. 
* It rearranges the search order for a URL to ID match to home_url first, if so searches for the Indieweb single author property, then searches whether it is a single user site, then searches for author post URL, and finally it does the meta query to search for the URL in user_url.
* It adds a filter to automatically add the trailing slash to all user_urls to ensure that it is always there when inserted into the database
* It adds testing
* Fixes a typo, redirect_url instead of redirect_uri
* Changes the settings page to allow for two presets(local or indieauth), or a custom option
* Adds functions to get the endpoints, instead of directly calling for the option.
* If there is no user_url, it will return the author post url as the 'me' parameter.
* Removes requirement for parameters from the REST call and add check inside the function so it will return the OAuth Error Response instead of the WP Error response.
* Adds a new debug function that will show the Indieauth requests in the error log if WP_DEBUG is enabled, specifically blanking the code and token data.

### CODE REVIEW

**Comment by pfefferle** [comment]
I changed the form a bit, what do you think?

**Comment by dshanske** [comment]
I like it. What do you think of the other changes?

**Comment by pfefferle** [comment]
looks good to me... but I didn't check the functionality...

**Review by pfefferle — APPROVED** [review]

**Comment by dshanske** [comment]
What do we need to do to push this to wordpress.org?

**Comment by pfefferle** [comment]
merge it and then I can make a tag!

**Comment by pfefferle** [comment]
is the latest version tested? can I release the 2.0.0 version?

**Comment by dshanske** [comment]
I am using it actively.

**Pull request merged**
