### PR TITLE
Client Information Discovery

### PR DESCRIPTION
**Pull request by dshanske**
https://github.com/indieweb/indieauth/issues/23

Per this discussion, this PR is the intiial attempt to find info on the client_id page to enhance the token.

### CODE REVIEW

**Review by pfefferle — COMMENTED** [review]
I would prefer the other way around: the setter/parser should select one single icon, the name, ... and the getter should only return the string.

**Comment by dshanske** [comment]
@pfefferle Does this address your request? Everything is now private except direct retrieval.

**Review by pfefferle — APPROVED** [review]
👍

**Comment by dshanske** [comment]
Ready for a release, you think?

**Comment by pfefferle** [comment]
sure, release fast, release often!

**Pull request merged**
