### PR TITLE
Use single quotes for auth test html attrs

### LINKED ISSUE #158: "Authorization has Failed" message shows up, but login works fine
On my test-server I see the "Authorization has Failed" error message, but the authentication works fine, so either the message shouldn't be displayed or the login should have failed.

It would also be nice to have a "I have seen the message" button, to hide the error.

### LINKED ISSUE #188: Authorization has failed!
Newbie-Question:
I did install the IndieAuth-plugin and do get the following site-health-message:

_Authorization has Failed
The authorization header was not returned on this test, which means that your server may be stripping the Authorization header. This is needed for IndieAuth to work correctly.

If you are on Apache, try adding this line to your .htaccess file:

SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

If that doesnt work, try this:

RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

If that does not work either, you may need to ask your hosting provider to reconfigure to allow the Authorization header to be passed. If they refuse, you can pass it through Apache with an alternate name. The plugin searches for the header in REDIRECT_HTTP_AUTHORIZATION, as some FastCGI implementations store the header in this location._

I did test the suggested .htaccess-lines. But there was no change in the result. My hoster is all-inkl.com. Sorry, I am not a software-developer. But maybe you will be able to give a hint to this. Thanks!
regards,
Suitbert

### LINKED ISSUE #201: WordPress site health status "Authorization has Failed"
This is what I get:

```
Authorization has Failed

The authorization header was not returned on this test, which means that your server may be stripping the Authorization header. This is needed for IndieAuth to work correctly.

If you are on Apache, try adding this line to your .htaccess file:

`SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1`

If that doesnt work, try this:

`RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]`

If that does not work either, you may need to ask your hosting provider to reconfigure to allow the Authorization header to be passed. If they refuse, you can pass it through Apache with an alternate name. The plugin searches for the header in REDIRECT_HTTP_AUTHORIZATION, as some FastCGI implementations store the header in this location.
```

I tested both codes/commands it said and the error doesn't go away. I asked my provider and he says everything is fine.

### LINKED ISSUE #204: Missing authorization cod for IndieAuth plugin
Since the IndieAuth plugin was upgraded I got this notification
Authorization has Failed
The authorization header was not returned on this test, which means that your server may be stripping the Authorization header. This is needed for IndieAuth to work correctly.

If you are on Apache, try adding this line to your .htaccess file:

SetEnvIf Authorization "(.*)" HTTP_AUTHORIZATION=$1

If that doesnt work, try this:

RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

If that does not work either, you may need to ask your hosting provider to reconfigure to allow the Authorization header to be passed. If they refuse, you can pass it through Apache with an alternate name. The plugin searches for the header in REDIRECT_HTTP_AUTHORIZATION, as some FastCGI implementations store the header in this location.

If contacting your hosting provider does not work you can open an issue on GitHub and we will try to assist

I have not been able to get it fixed

Realmsuncharted from NameCheap hosted on Stablehost.

### PR DESCRIPTION
**Pull request by chee**
should fix #204, close #201 and fix #188 and close #158

### CODE REVIEW

**Comment by pfefferle** [comment]
Can you explain why the quotes are causing this issue?

**Comment by dshanske** [comment]
I thought I might have messed up the sanitizing when I did that PR... might switch to using built in WordPress functions as I did elsewhere.

**Comment by chee** [comment]
@pfefferle  Yes, sorry: the quotes are causing the issue because when this is output it is inside JSON.
I mentioned it here: https://github.com/indieweb/wordpress-indieauth/issues/204#issuecomment-845904829

> the returned response has a div with a class, and uses the double quote. so the json is invalid:
> 
> ```json
>   {"message":"<div class="notice notice-success"><p>Authorization Header Found. You should be able to use all clients."}
> ```

the double quote becomes a closing quote for the `message` property's value

**Comment by chee** [comment]
i've added that info to the commit message:)

**Comment by dshanske** [comment]
Closed as implemented using esc_html

**Pull request closed without merging**
