### PR TITLE
Clients

### PR DESCRIPTION
**Pull request by dshanske**
Introduce a Taxonomy to store client data and relevant functions

### CODE REVIEW

**Review by tw2113 — APPROVED** [review]

**Comment by pfefferle** [comment]
Is it really a good idea to use a taxonomy to save client data? If you do not want to use custom tables I even would prefer to use custom post types.

**Comment by dshanske** [comment]
@pfefferle I'm attaching it to posts made via Micropub. It allows for proper attribution of posts

**Comment by dshanske** [comment]
I debated where to store it for a bit.

**Comment by tw2113** [comment]
post to post isn't as straightforward for post content association as compared to taxonomy term/term meta and even then just post meta. At least term meta has some indexing available to it by way of terms. In the end it feels like a micro-optimization of where to store data for a given content type, and how much data is already generally queried for by default vs what would be extra.

Less a question of "best practice" in my mind, and more of "best preferred" question.

**Comment by dshanske** [comment]
Still thinking about this.

**Review by pfefferle — APPROVED** [review]
I saw this more and more often lately... maybe this is really the way to go...

**Comment by dshanske** [comment]
I have to go remind myself what I did, but might be time for a release.

**Pull request merged**
