### PR TITLE
Refactor in Search of Fixes

### PR DESCRIPTION
**Pull request by dshanske**
@pfefferle This seemed to solve your issue of local login...I tested it and was able to log into my test site using my live site.

I also added a series of extra checks for some of the errors people were experiencing, even though I could not reliably reproduce them all.

### CODE REVIEW

**Comment by miklb** [comment]
I can confirm using the master branch of micropub & this branch that most of my issues are resolved save the error in Omnibear. But I am now able to authenticate and post from Quill.

These fixes also passed the 800 tests in micropub.rocks (I'm not sure where one fix stops and another begins however)

**Comment by pfefferle** [comment]
I still get "Invalid authorization code".

**Comment by dshanske** [comment]
In the hooks branch?

**Comment by dshanske** [comment]
I logged into my test site with the endpoint set to my live site.

**Comment by dshanske** [comment]
You are keeping each site's configuration on local or custom?

**Comment by pfefferle** [comment]
I tried the code of this merge request and both sites using „build in endpoints“

**Comment by pfefferle** [comment]
OK, this seems to be the problem: https://github.com/dshanske/wordpress-indieauth/blob/hooks/includes/class-indieauth-authenticate.php#L261

**Comment by pfefferle** [comment]
Local endpoint does not mean that you can do a local lookup! You have to check if the redirect domain is the same as the blog domain or something similar.

**Comment by pfefferle** [comment]
I will try to explain my use case once again, but from my perspective it is the only valid use case for an indieauth login, it is how OpenID and IndieLogin works.

Use case: We have https://indiewp.com, a multiuser blog. This blog is set to local endpoints, but this doesn't matter, because these settings should never be used for this flow.

You should be able to login using `david.shanske.com` and I should be able to login with `notiz.blog` so  indiewp.com always has to verify the `code` against the remote endpoints and never use his own!

**Comment by pfefferle** [comment]
I think we discussed a lookup against the local DB but I think this was in another context... I think it was something with the token endpoint...

**Comment by pfefferle** [comment]
@aaronpk am I wrong?

**Comment by aaronpk** [comment]
I think this is confusing because you're trying to have this plugin do two things. 

1) This plugin is an IndieAuth authorization server when signing in to other apps
2) This plugin also authenticates users using their own IndieAuth server

Again this is why I was trying to have you document the use cases clearly so that we had something to reference while testing the changes.

**Comment by pfefferle** [comment]
@aaronpk I can document this, but isn't this the normal case?

**Comment by aaronpk** [comment]
I don't know what you mean by "normal case". Certainly some users will only ever sign in to their wordpress with a username and password, and will never use number 2 above. I expect once this plugin is stable, that number 1 above will be the most common case, for signing in to other apps using someone's own wordpress site as their identity.

**Comment by pfefferle** [comment]
@aaronpk don't get me wrong... I am not really heavily using this feature, but it is part of the plugin, so I tried to test every possibility...

**Comment by pfefferle** [comment]
@aaronpk with "normal" I meant the "normal IndieAuth login flow".

**Review by pfefferle — CHANGES_REQUESTED** [review]
remove the local verification code

```php
if ( 'local' === $option ) {
	$params = self::verify_local_authorization_code( $post_args );
}
```

**Comment by dshanske** [comment]
@pfefferle That isn't a new feature. It was already there. Shouldn't that be a separate PR to revert that change?

**Comment by dshanske** [comment]
@pfefferle I tried to find a middle ground. It looks to see if the endpoint is on the same site, which would mean it can be verified locally.

**Comment by pfefferle** [comment]
Thanks for the quick fix, but is this really a case? That you use david.shanske.com to log in to david.shanske.com using IndieAuth? Because it ends up in a redirect hell and in the end you have to use your login and password anyways. But yes it should work.

But you forgot one check... there were two of these checks in the code, I think!

**Comment by dshanske** [comment]
The other one doesn't check for an endpoint

**Comment by pfefferle** [comment]
That‘s why I would prefer to remove it. The Web Sign-In should never use the local verification.

**Comment by dshanske** [comment]
Should removing the change be in this PR or a separate one?

**Comment by pfefferle** [comment]
I have no preferences for that 😉

**Comment by pfefferle** [comment]
But I would vote for a minor update instead of a patch, after so many changes.

**Comment by aaronpk** [comment]
People have definitely installed this plugin with the intent to log in to their site via Twitter RelMeAuth using the same domain.

**Comment by dshanske** [comment]
So, should we be supporting that, aaronpk?

**Comment by dshanske** [comment]
Indielogin isn't a good idea till aaronpk opens it up

**Comment by pfefferle** [comment]
What do you mean with „open it up“?

**Comment by aaronpk** [comment]
Right now indielogin.com is in beta, and I'm not opening it up for other developers to use that instance just yet. (It's open source so of course you could host your own.) Once I finish email login (and maybe PGP authentication) I'll launch it. However I am also considering requiring that people sign up as a developer in order to use it once it's live, since that will help avoid getting into the situation we're in with indieauth.com now. I could see about making an account for this wordpress plugin though.

**Review by pfefferle — APPROVED** [review]

**Pull request merged**
